# Stage 1: Build Angular App
FROM node:22 AS node-builder
WORKDIR /app
COPY ClientApp ./ClientApp
WORKDIR /app/ClientApp
RUN npm install
RUN npm run build-prod
#RUN npm run build-local

# Stage 2: Build .NET Core App
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY . .
COPY --from=node-builder /app/ClientApp/dist/WebModuleTeko /src/wwwroot
RUN dotnet restore
RUN dotnet publish -c Release -o /app/publish -p:BuildSwag=false

# Stage 3: Runtime
FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 80
ENTRYPOINT ["dotnet", "WebModuleTeko.dll"]