name: Tela Fly Deploy

on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Fly CLI
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "${HOME}/.fly/bin" >> $GITHUB_PATH

      - name: Fly Deploy
        working-directory: fly/webmodule
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_TOKEN }}
        run: |
          flyctl deploy --remote-only
